name: kanakupulla
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 1.2.1+2

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  sqflite: any
  path: any
  shared_preferences: ^2.0.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.3.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  file_picker: ^8.0.0
  speech_to_text: ^7.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  local_auth: ^2.3.0
  google_mlkit_text_recognition: ^0.13.0
  home_widget: ^0.7.0
  table_calendar: ^3.1.0
  google_sign_in: ^6.1.0
  googleapis: ^11.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  flutter_contacts: ^1.1.9+2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/kplogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/kplogo.png
# ...existing code...
